include ${TERRAFORM_DIR}/modules.mk

MODULES = azure/resource-group								\
		  azure/key-vault									\
		  azure/key-vault-key								\
		  confluent/byok									\
		  azure/vpc											\
		  confluent/environment								\
		  confluent/network									\
		  confluent/private-link							\
		  azure/private-link								\
		  confluent/cluster									\
		  azure/aks											\
		  azure/app-registration 							\
		  azure/managed-identity							\
		  azure/federated-managed-identity					\
		  confluent/identity-provider						\
		  confluent/identity-pool-topic-owner				\
		  confluent/identity-pool-topic-owner-permission	\
		  confluent/identity-pool-producer					\
		  confluent/identity-pool-producer-permission		\
		  confluent/identity-pool-consumer					\
		  confluent/identity-pool-consumer-permission
